import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Rahul Singh',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Puma',
        logo: '/images/logo1.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'Prasana',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Sponge Gourd",
      category: 'fruits & vegetables',
      image:'/images/SpongeGourd.jpeg',
      price: 51.09,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
   },
   {
      name: "Baby corn cleaned",
      category: 'fruits & vegetables',
      image:'/images/Babycorncleaned.jpg',
      price: 151.18,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
   },
   {
      name: "Baby corn",
      category: 'fruits & vegetables',
      image:'/images/Babycorn.jpg',
      price: 33.40,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
   },
   {
      name: "Chilakarive green",
      category: 'fruits & vegetables',
      image:'/images/Chilakarivegreen.png',
      price: 34.24,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
   },
   {
      name: "Chakota greens",
      category: 'fruits & vegetables',
      image:'/images/Chakotagreens.jpg',
      price: 50.90,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
   },
   {
      name: "Eggs",
      category: 'fruits & vegetables',
      image:'/images/Eggs.jpg',
      price: 6.60,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
   },
   {
      name: "Arive greens",
      category: 'fruits & vegetables',
      image:'/images/Arivegreens.jpeg',
      price: 48.72,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
   },
   {
      name: "knol-khol",
      category: 'fruits & vegetables',
      image:'/images/knol-khol.jpg',
      price: 43.60,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
   },
   {
      name: "Chikadi kai",
      category: 'fruits & vegetables',
      image:'/images/Chikadikai.jpg',
      price: 65.17,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
   },
   {
      name: "Garlic cleaned",
      category: 'fruits & vegetables',
      image:'/images/Garliccleaned.jpeg',
      price: 222.76,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
   },
   {
      name: "Garlic",
      category: 'fruits & vegetables',
      image:'/images/Garlic.jpg',
      price: 141.53,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
   },
   {
      name: "Ginger",
      category: 'fruits & vegetables',
      image:'/images/Ginger.jpg',
      price: 64.63,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
   },
   {
      name: "Ground nut Local",
      category: 'fruits & vegetables',
      image:'/images/GroundnutLocal.jpg',
      price: 103.40,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
   },
   {
    name: "Double Beans",
    category: 'fruits & vegetables',
    image:'/images/DoubleBeans.jpeg',
    price: 111.96,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 10,
    description: 'high quality product',
 },
 {
    name: "DoubleBeansseeds",
    category: 'fruits & vegetables',
    image:'/images/Double Beans seeds.jpeg',
    price: 213.40,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 10,
    description: 'high quality product',
 },{
   name: "Drumstik",
   category: 'fruits & vegetables',
   image:'/images/Drumstik.jpg',
   price: 112.13,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Cauliflower per Kg",
   category: 'fruits & vegetables',
   image:'/images/Cauliflower.jpg',
   price: 59.00,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Cauliflower(M)",
   category: 'fruits & vegetables',
   image:'/images/Cauliflower.jpg',
   price: 39.13,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mushroom Button",
   category: 'fruits & vegetables',
   image:'/images/MushroomButton.jpg',
   price: 305.55,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Grapes Dry 250gm",
   category: 'fruits & vegetables',
   image:'/images/GrapesDry.jpg',
   price: 131.18,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Grapes Red globe",
   category: 'fruits & vegetables',
   image:'/images/GrapesRedglobe.jpg',
   price: 505.72,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Lime Local",
   category: 'fruits & vegetables',
   image:'/images/limelocal.jpeg',
   price: 126.34,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Little gourd",
   category: 'fruits & vegetables',
   image:'/images/littlegourd.jpg',
   price: 34.41,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Ladys finger",
   category: 'fruits & vegetables',
   image:'/images/ladysfinger.jpeg',
   price: 63.09,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Herali kai",
   category: 'fruits & vegetables',
   image:'/images/heralikai.jpg',
   price: 89.25,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Grapes T.S.",
   category: 'fruits & vegetables',
   image:'/images/Grapes.jpg',
   price: 131.70,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Avarekai (Field Beans )",
   category: 'fruits & vegetables',
   image:'/images/avarekai.jpg',
   price: 66.19,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Banana cooking R.Banana",
   category: 'fruits & vegetables',
   image:'/images/BananaCooking.jpeg',
   price: 66.27,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Jukani",
   category: 'fruits & vegetables',
   image:'/images/jukani.jpg',
   price: 174.43,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Sham gadde",
   category: 'fruits & vegetables',
   image:'/images/shamgadde.jpg',
   price: 75.37,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Snake Gourd(S)",
   category: 'fruits & vegetables',
   image:'/images/snakegourds.jpg',
   price: 34.99,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Snake Gourd",
   category: 'fruits & vegetables',
   image:'/images/snakegourds.jpg',
   price: 43.51,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Raddish Red",
   category: 'fruits & vegetables',
   image:'/images/raddishred.jpg',
   price: 62.81,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Raddish",
   category: 'fruits & vegetables',
   image:'/images/raddish.jpg',
   price: 36.92,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Sweet Potato(Genasu)",
   category: 'fruits & vegetables',
   image:'/images/sweetpotato.jpeg',
   price: 48.97,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Potato(B)",
   category: 'fruits & vegetables',
   image:'/images/potatoB.jpeg',
   price: 32.43,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Potato(M)",
   category: 'fruits & vegetables',
   image:'/images/potatoM.jpg',
   price: 40.21,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Pumpkin Japan",
   category: 'fruits & vegetables',
   image:'/images/pumpkinjapan.webp',
   price: 26.12,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Pumpkin Red",
   category: 'fruits & vegetables',
   image:'/images/pumpkinred.jpeg',
   price: 20.73,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Pumpkin Ash",
   category: 'fruits & vegetables',
   image:'/images/pumpkinash.jpg',
   price: 23.14,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Orange malt",
   category: 'fruits & vegetables',
   image:'/images/orangemalt.jpg',
   price: 73.88,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Grapes Blore blue",
   category: 'fruits & vegetables',
   image:'/images/grapesbloreblue.jpeg',
   price: 59.93,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Guava Allahabad(Red)",
   category: 'fruits & vegetables',
   image:'/images/guavaallahabaadred.jpeg',
   price: 96.96,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Guava",
   category: 'fruits & vegetables',
   image:'/images/guava.jpeg',
   price: 72.64,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Chicco(Sapota)",
   category: 'fruits & vegetables',
   image:'/images/chicoo.jpeg',
   price: 55.76,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Custerd Apple",
   category: 'fruits & vegetables',
   image:'/images/custurdapple.jpeg',
   price: 54.17,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Chicco(Sapota) rapined",
   category: 'fruits & vegetables',
   image:'/images/chicoorapined.jpeg',
   price: 62.82,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Banana Rasabale",
   category: 'fruits & vegetables',
   image:'/images/bananarasable.jpeg',
   price: 63.84,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Banana Nendra",
   category: 'fruits & vegetables',
   image:'/images/banananendra.jpeg',
   price: 78.59,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Banana chandra",
   category: 'fruits & vegetables',
   image:'/images/bananachandra.webp',
   price: 80.99,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Banana Yellaki",
   category: 'fruits & vegetables',
   image:'/images/bananayellaki.jpeg',
   price: 80.83,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Banana pachabale",
   category: 'fruits & vegetables',
   image:'/images/bananapatchable.jpeg',
   price: 33.84,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Apple Green smith",
   category: 'fruits & vegetables',
   image:'/images/applegreensmith.jpeg',
   price: 350.28,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Apple Fuji chaina",
   category: 'fruits & vegetables',
   image:'/images/applefujichina.jpg',
   price: 290.33,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Apple Newzeland",
   category: 'fruits & vegetables',
   image:'/images/applenewzeland.jpg',
   price: 298.81,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Apple Washington",
   category: 'fruits & vegetables',
   image:'/images/applewashington.jpg',
   price: 310.14,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Apple Economy",
   category: 'fruits & vegetables',
   image:'/images/appleeconomy.jpeg',
   price: 159.34,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Apple Delicious",
   category: 'fruits & vegetables',
   image:'/images/appledelicious.jpg',
   price: 186.10,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Palak Greens",
   category: 'fruits & vegetables',
   image:'/images/palakgreens.jpg',
   price: 54.72,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Menthya Greens",
   category: 'fruits & vegetables',
   image:'/images/menthyagreens.png',
   price: 85.29,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mint Leaves",
   category: 'fruits & vegetables',
   image:'/images/mintleaves.jpeg',
   price: 58.24,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "G.nut oil Rice Bron 1 lt",
   category: 'fruits & vegetables',
   image:'/images/groundoilricebron.jpg',
   price: 139.11,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "G.nut oil Premium1 lt",
   category: 'fruits & vegetables',
   image:'/images/groundnutoilpremium.jpeg',
   price: 163.80,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Ground nut oil 1 lt",
   category: 'fruits & vegetables',
   image:'/images/groundnutoil.jpeg',
   price: 158.49,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "G.oil Net rich 500 ml",
   category: 'fruits & vegetables',
   image:'/images/groundnutoilnetrich500.jpg',
   price: 78.14,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Fruit Juice Tailand",
   category: 'fruits & vegetables',
   image:'/images/fruitjuice.jpg',
   price: 21.42,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Tender Coconut(S)",
   category: 'fruits & vegetables',
   image:'/images/tendercoconut.jpg',
   price: 25.85,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Pista",
   category: 'fruits & vegetables',
   image:'/images/pista.jpg',
   price: 178.48,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Thinda",
   category: 'fruits & vegetables',
   image:'/images/thinda.jpg',
   price: 74.23,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Tamarind seedless",
   category: 'fruits & vegetables',
   image:'/images/tamarindseedless.jpeg',
   price: 195.71,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "StrawBerry",
   category: 'fruits & vegetables',
   image:'/images/strawberry.jpg',
   price: 144.56,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Litchi Local",
   category: 'fruits & vegetables',
   image:'/images/litchilocal.jpeg',
   price: 331.86,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Kiwi fruit",
   category: 'fruits & vegetables',
   image:'/images/kiwi.jpeg',
   price: 521.36,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Grapes Krishna sharad",
   category: 'fruits & vegetables',
   image:'/images/grapeskrishnasharad.jpg',
   price: 148.26,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{ 
   name: "Grapes Flame",
   category: 'fruits & vegetables',
   image:'/images/grapesflame.jpg',
   price: 105.46,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Grapes Sonika",
   category: 'fruits & vegetables',
   image:'/images/grapessonika.jpg',
   price: 137.48,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Grapes Sharad",
   category: 'fruits & vegetables',
   image:'/images/grapessharad.jpeg',
   price: 139.23,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Grapes Dilkush",
   category: 'fruits & vegetables',
   image:'/images/grapesdilkhush.webp',
   price: 85.26,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Grapes Anabi shahi",
   category: 'fruits & vegetables',
   image:'/images/grapesanabishahi.jpg',
   price: 28.36,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Hesaru kalu",
   category: 'fruits & vegetables',
   image:'/images/hesarukalu.jpeg',
   price: 141.41,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Molake kalu",
   category: 'fruits & vegetables',
   image:'/images/molakekalu.jpg',
   price: 114.82,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Greens Sabbakki",
   category: 'fruits & vegetables',
   image:'/images/greenssabbakki.jpg',
   price: 77.08,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
// {
//    name: "Parvala",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 100.79,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
{
   name: "Spring Onion(Cleaned)",
   category: 'fruits & vegetables',
   image:'/images/springonioncleaned.jpg',
   price: 86.91,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Spring Onion",
   category: 'fruits & vegetables',
   image:'/images/springonion.jpg',
   price: 83.97,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Chocolates Drink box",
   category: 'fruits & vegetables',
   image:'/images/chocolatesdrinkbox.jpg',
   price: 53.53,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Fanda",
   category: 'fruits & vegetables',
   image:'/images/fanda.jpeg',
   price: 44.64,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
// {
//    name: "Jam 100 gm",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 26.75,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Jam 200 gm",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 44.60,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
{
   name: "Jam 1/2 kg",
   category: 'fruits & vegetables',
   image:'/images/jam.jpeg',
   price: 98.17,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
// {
//    name: "Jam 1 kg",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 133.84,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
{
   name: "Coconut oil 500 ml",
   category: 'fruits & vegetables',
   image:'/images/coconutoil.jpeg',
   price: 126.52,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Stevia powder",
   category: 'fruits & vegetables',
   image:'/images/steviapowder.jpeg',
   price: 107.08,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Pepper",
   category: 'fruits & vegetables',
   image:'/images/peeper.jpeg',
   price: 124.91,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Sungold oil 5 lt packet",
   category: 'fruits & vegetables',
   image:'/images/sungoldoil.jpg',
   price: 713.87,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
// {
//    name: "Sun safal Tin 15 lt",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 845.91,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Safal deep 500 ml",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 66.70,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Ground nut oil 5 lt",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 1007.24,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Sungold oil 5 lt",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 765.01,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Rice Bran 5 lt",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 716.54,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Tamarind Paste 150 gm",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 61.91,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Indian red globe",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 214.06,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Peas seeds",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 305.86,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Anjura/Fig",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 115.76,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Butter fruit",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 138.76,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Bore fruit",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 36.44,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "S.mellon Local (Luck)",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 59.48,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Chilles small cleaned (C.B.P)",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 99.74,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Times Rose berry",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 218.49,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Chikkadikai cleaned",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 75.89,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Orange juice",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 24.98,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Thiland Jelly",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 35.69,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Thiland Juice",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 21.41,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Pineapple juice",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 117.80,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Mosambi",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 91.72,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "S.mellon namdhari",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 34.62,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Watermellon kiran",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 29.97,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Watermellon",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 25.09,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Tamarind sweet 500gm",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 184.04,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Rose apple",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 243.24,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Plum Australia",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 533.22,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Pineapple",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 64.88,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Papaya sola",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 59.72,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Papaya Red lady",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 36.20,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Papaya Taiwan",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 34.65,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Papaya nati",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 22.90,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Pomegranate A.raktha",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 153.07,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Pomegranate Bhagav",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 225.26,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Dhantu greens",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 55.07,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Curry leave",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 85.26,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Corriander Leave",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 63.20,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Kakadi",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 78.57,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Pickles mixed veg",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 89.24,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "mango Pickles",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 107.08,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Lime Pickles",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 116.03,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Pickles",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 98.14,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Rice Bran 15 lt Tin",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 1424.26,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "G. nut sungold 1 lt",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 150.04,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "G. nut Golden oil 1 lt",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 197.79,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "G. nut oil safal deep1 lt",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 130.89,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Apple juice",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 117.81,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Litchi Juice",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 117.80,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Parsley",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 278.62,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Leeks",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 224.12,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Selari",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 185.66,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Chikkadikai Round",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 55.64,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Mineral water 1 lt",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 26.75,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Net rich 5 lt oil",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 526.65,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Byladha Hannu",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 48.66,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Maize",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 27.21,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Y.Bananan T.N.",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 256.29,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Chain Berry",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 187.93,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Letteus Greens",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 193.17,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Basale Greens",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 56.09,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "BaleDindu (Banana stem)",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 35.62,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Batani kalu",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 352.42,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Sweet corn",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 55.80,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Orange Australia",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 200.13,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Orange Nagpura",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 99.14,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Cluster Bean Local",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 49.17,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Mangalore cucumber",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 30.35,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Cucumber Israle",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 55.69,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Cucumber Nati",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 54.49,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Cucumber",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 31.18,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Chow-Chow",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 41.11,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Bottle Gourd",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 36.00,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Dry fruit mixed",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 151.62,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Dry dates",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 185.92,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Peas Delhi",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 90.67,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Peas local",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 223.98,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Onion samber",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 86.25,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Onion small(Economy)",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 17.45,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Jack fruit",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 26.63,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Onion Big",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 44.33,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Onion medium",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 40.93,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Mushroom Oyster",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 179.17,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Brucoli",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 294.39,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Avare seed (FB seeds)",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 156.40,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Avarebele (F. Beans spok)",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 281.52,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Bale hoovu(B.flower)",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 33.42,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Sweet corn seeds",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 84.10,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Kashini (Ganike) Greens",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 13.67,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Gulkan 1/4 kg",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 53.59,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Gulkan 1/2 kg",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 71.39,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Gulkan 1 kg",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 142.72,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Honney 100 gm",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 51.74,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Honney 200 gm",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 96.35,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Honney 1 Kg",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 342.67,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Honney 1/2",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 187.46,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Copra",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 188.57,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Cauliflower(B)",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 47.74,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Cabbage chaina",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 82.72,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Cabbage Red",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 92.99,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Cabbage",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 28.39,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Coconut (OS)",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 18.27,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Coconut (S)",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 23.69,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Coconut (M)",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 30.01,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Coconut (B)",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 34.59,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Cowpea Long",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 71.59,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Carrot Nati",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 61.12,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Carrot Delhi",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 46.87,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Chillies small (C.B.P)",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 96.63,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Chillies Cleaned",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 55.80,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Chillies Bajji",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 53.80,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Chillies Green",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 56.93,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Capsicum Red/Yellow",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 160.66,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Capsicum",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 60.62,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Mango Raw",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 68.15,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Thogari kai",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 52.89,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Tomoto",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 30.27,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Bitter Gourd",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 48.74,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Yam/S.Root",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 59.70,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Beet Root",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 41.76,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Brinjal Bottle",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 54.55,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Brinjal (R)",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 37.06,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Brinjal (W)",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 48.96,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Beans cleaned",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 68.52,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Beans",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 66.71,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// // {
// //    name: "Amla",
// //    category: 'fruits & vegetables',
// //    image:'/images/Sponge Gourd.jpeg',
// //    price: 89.07,
// //    countInStock: 10,
// //    brand: 'Nike',
// //    rating: 4.5,
// //    numReviews: 10,
// //    description: 'high quality product',
// // },
// // {
// //    name: "N.Juice 200 ml",
// //    category: 'fruits & vegetables',
// //    image:'/images/Sponge Gourd.jpeg',
// //    price: 26.75,
// //    countInStock: 10,
// //    brand: 'Nike',
// //    rating: 4.5,
// //    numReviews: 10,
// //    description: 'high quality product',
// // },
// // {
// //    name: "Pomegranate Juice",
// //    category: 'fruits & vegetables',
// //    image:'/images/Sponge Gourd.jpeg',
// //    price: 117.77,
// //    countInStock: 10,
// //    brand: 'Nike',
// //    rating: 4.5,
// //    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Brahmi amla juice",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 124.97,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Jumbu juice",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 223.13,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
{
   name: "G. nut oil Rice 1 lt",
   category: 'fruits & vegetables',
   image:'/images/groundnutoilricebron.jpeg',
   price: 107.52,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
// {
//    name: "Onion flowers",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 34.78,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Pomegranate Ganesh",
//    category: 'fruits & vegetables',
//    image:'/images/.jpeg',
//    price: 119.09,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Grapesh Tash ganesh",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 107.37,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Peas Dharwad",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 14.16,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Papaya red indian",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 37.17,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Peas Ooty",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 124.08,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Grapes Crimson",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 48.99,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
{
   name: "Indian Black globe Grapes",
   category: 'fruits & vegetables',
   image:'/images/Grapes.jpg',
   price: 145.78,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
// {
//    name: "Nagapur Orange Economy",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 9.76,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Mango thotapuri",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 53.55,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Mango Sendura",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 47.21,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "S.mellon namdhari (Red)",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 35.43,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Cucumber white",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 34.92,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Mango Alphans",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 72.85,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Mango Raw Amblet",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 54.77,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Mango Badami",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 68.12,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Mango Raspuri",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 52.83,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "South Af.red berry",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 368.52,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Apple Chilli",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 149.32,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Carrot ooty",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 71.97,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Mango Bygan palli",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 50.12,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Mango malagova",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 80.01,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Cluster Beans Bunches",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 25.77,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Mango mallika",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 73.73,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Mango Dasheri",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 64.26,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Mango kalapadu",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 46.50,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Litchi Taiwan/chaina",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 369.55,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Mango sakkaregutti",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 40.75,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Rumenia Mango",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 74.14,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
{
   name: "Apple Chaina Delicious",
   category: 'fruits & vegetables',
   image:'/images/applefujichina.jpg',
   price: 264.54,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
// {
//    name: "Mango Amarpalli",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 40.72,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Mango Kesar",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 40.83,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Mango",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 23.46,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Jambo fruit(Nerale)",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 282.98,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Mango Neelam",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 47.16,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Grapes Rose",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 71.34,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Berry fruit Ooty",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 26.64,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Plum Ooty",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 180.18,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Orange",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 60.97,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Beans Fruit",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 69.99,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Apple hazarath palli",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 154.60,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Peaches",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 258.89,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Komark fruit",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 38.58,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Sweet corn seeds spok",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 49.95,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Berry Golden",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 287.02,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Apple Simla",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 122.57,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Ginger New",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 83.62,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Cherry Tomoto",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 121.79,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Tamrind Chatisghar",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 103.91,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
{
   name: "Tender Coconut",
   category: 'fruits & vegetables',
   image:'/images/tendercoconut.jpg',
   price: 33.45,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
// {
//    name: "Mango rathnagiri(red)",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 32.57,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Berry Southafrica",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 211.33,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Mango Alphans box",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 116.42,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Bread fruit",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 73.35,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Apple Australia",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 188.52,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
{
   name: "Potato Baby",
   category: 'fruits & vegetables',
   image:'/images/potatoB.jpeg',
   price: 52.38,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
// {
//    name: "Orange South Africa",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 148.57,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
{
   name: "Apple Golden delicious",
   category: 'fruits & vegetables',
   image:'/images/appledelicious.jpg',
   price: 95.45,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
// {
//    name: "Washington gala apple",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 160.07,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Pomello/Chakotha",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 40.30,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "South Africa Gala apple",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 47.46,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Berry Soft",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 209.21,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Berry Green",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 224.57,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
{
   name: "Washington red apple",
   category: 'fruits & vegetables',
   image:'/images/applewashington.jpg',
   price: 126.41,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
// {
//    name: "Dry apricot",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 20.02,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Berry ball",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 92.22,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Cherry kashmir",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 497.87,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Sweet corn cleaned",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 125.14,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
{
   name: "Tamarind Paste 450 gm",
   category: 'fruits & vegetables',
   image:'/images/tamarindpaste.jpeg',
   price: 164.01,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
// {
//    name: "Cucumber Ooty",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 212.01,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Mosambi polo",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 31.04,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Beans Nati",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 28.14,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Orange Ooty",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 76.75,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Mango Langada",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 57.70,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Beans Ring",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 23.58,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Cherry fruit",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 110.77,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
// {
//    name: "Chillies Bajji yagani",
//    category: 'fruits & vegetables',
//    image:'/images/Sponge Gourd.jpeg',
//    price: 51.25,
//    countInStock: 10,
//    brand: 'Nike',
//    rating: 4.5,
//    numReviews: 10,
//    description: 'high quality product',
// },
{
   name: "Tender Coconut(M)",
   category: 'fruits & vegetables',
   image:'/images/tendercoconut.jpg',
   price: 27.16,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
}

  ],
};
export default data;