import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Rahul Singh',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Puma',
        logo: '/images/logo1.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'Prasana',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Sponge Gourd",
      category: 'Shirts',
      image:'/images/SpongeGourd.jpeg',
      price: 51.09,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
   },
   {
      name: "Baby corn cleaned",
      category: 'Shirts',
      image:'/images/Babycorncleaned.jpg',
      price: 151.18,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
   },
   {
      name: "Baby corn",
      category: 'Shirts',
      image:'/images/Babycorn.jpg',
      price: 33.40,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
   },
   {
      name: "Chilakarive green",
      category: 'Shirts',
      image:'/images/Chilakarivegreen.png',
      price: 34.24,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
   },
   {
      name: "Chakota greens",
      category: 'Shirts',
      image:'/images/Chakotagreens.jpg',
      price: 50.90,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
   },
   {
      name: "Eggs",
      category: 'Shirts',
      image:'/images/Eggs.jpg',
      price: 6.60,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
   },
   {
      name: "Arive greens",
      category: 'Shirts',
      image:'/images/Arivegreens.jpeg',
      price: 48.72,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
   },
   {
      name: "knol-khol",
      category: 'Shirts',
      image:'/images/knol-khol.jpg',
      price: 43.60,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
   },
   {
      name: "Chikadi kai",
      category: 'Shirts',
      image:'/images/Chikadikai.jpg',
      price: 65.17,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
   },
   {
      name: "Garlic cleaned",
      category: 'Shirts',
      image:'/images/Garliccleaned.jpeg',
      price: 222.76,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
   },
   {
      name: "Garlic",
      category: 'Shirts',
      image:'/images/Garlic.jpg',
      price: 141.53,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
   },
   {
      name: "Ginger",
      category: 'Shirts',
      image:'/images/Ginger.jpg',
      price: 64.63,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
   },
   {
      name: "Ground nut Local",
      category: 'Shirts',
      image:'/images/GroundnutLocal.jpg',
      price: 103.40,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
   },
   {
    name: "Double Beans",
    category: 'Shirts',
    image:'/images/DoubleBeans.jpeg',
    price: 111.96,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 10,
    description: 'high quality product',
 },
 {
    name: "DoubleBeansseeds",
    category: 'Shirts',
    image:'/images/Double Beans seeds.jpeg',
    price: 213.40,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 10,
    description: 'high quality product',
 },{
   name: "Drumstik",
   category: 'Shirts',
   image:'/images/Drumstik.jpg',
   price: 112.13,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Cauliflower per Kg",
   category: 'Shirts',
   image:'/images/Cauliflower.jpg',
   price: 59.00,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Cauliflower(M)",
   category: 'Shirts',
   image:'/images/Cauliflower.jpg',
   price: 39.13,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mushroom Button",
   category: 'Shirts',
   image:'/images/MushroomButton.jpg',
   price: 305.55,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Grapes Dry 250gm",
   category: 'Shirts',
   image:'/images/GrapesDry.jpg',
   price: 131.18,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Grapes Red globe",
   category: 'Shirts',
   image:'/images/GrapesRedglobe.jpg',
   price: 505.72,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Lime Local",
   category: 'Shirts',
   image:'/images/limelocal.jpeg',
   price: 126.34,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Little gourd",
   category: 'Shirts',
   image:'/images/littlegourd.jpg',
   price: 34.41,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Ladys finger",
   category: 'Shirts',
   image:'/images/ladysfinger.jpeg',
   price: 63.09,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Herali kai",
   category: 'Shirts',
   image:'/images/heralikai.jpg',
   price: 89.25,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Grapes T.S.",
   category: 'Shirts',
   image:'/images/Grapes.jpg',
   price: 131.70,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Avarekai (Field Beans )",
   category: 'Shirts',
   image:'/images/avarekai.jpg',
   price: 66.19,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Banana cooking R.Banana",
   category: 'Shirts',
   image:'/images/BananaCooking.jpeg',
   price: 66.27,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Jukani",
   category: 'Shirts',
   image:'/images/jukani.jpg',
   price: 174.43,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Sham gadde",
   category: 'Shirts',
   image:'/images/shamgadde.jpg',
   price: 75.37,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Snake Gourd(S)",
   category: 'Shirts',
   image:'/images/snakegourds.jpg',
   price: 34.99,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Snake Gourd",
   category: 'Shirts',
   image:'/images/snakegourds.jpg',
   price: 43.51,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Raddish Red",
   category: 'Shirts',
   image:'/images/raddishred.jpg',
   price: 62.81,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Raddish",
   category: 'Shirts',
   image:'/images/raddish.jpg',
   price: 36.92,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Sweet Potato(Genasu)",
   category: 'Shirts',
   image:'/images/sweetpotato.jpeg',
   price: 48.97,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Potato(B)",
   category: 'Shirts',
   image:'/images/potatoB.jpeg',
   price: 32.43,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Potato(M)",
   category: 'Shirts',
   image:'/images/potatoM.jpg',
   price: 40.21,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Pumpkin Japan",
   category: 'Shirts',
   image:'/images/pumpkinjapan.webp',
   price: 26.12,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Pumpkin Red",
   category: 'Shirts',
   image:'/images/pumpkinred.jpeg',
   price: 20.73,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Pumpkin Ash",
   category: 'Shirts',
   image:'/images/pumpkinash.jpg',
   price: 23.14,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Orange malt",
   category: 'Shirts',
   image:'/images/orangemalt.jpg',
   price: 73.88,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Grapes Blore blue",
   category: 'Shirts',
   image:'/images/grapesbloreblue.jpeg',
   price: 59.93,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Guava Allahabad(Red)",
   category: 'Shirts',
   image:'/images/guavaallahabaadred.jpeg',
   price: 96.96,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Guava",
   category: 'Shirts',
   image:'/images/guava.jpeg',
   price: 72.64,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Chicco(Sapota)",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 55.76,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Custerd Apple",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 54.17,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Chicco(Sapota) rapined",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 62.82,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Banana Rasabale",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 63.84,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Banana Nendra",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 78.59,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Banana chandra",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 80.99,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Banana Yellaki",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 80.83,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Banana pachabale",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 33.84,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Apple Green smith",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 350.28,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Apple Fuji chaina",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 290.33,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Apple Newzeland",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 298.81,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Apple Washington",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 310.14,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Apple Economy",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 159.34,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Apple Delicious",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 186.10,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Palak Greens",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 54.72,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Menthya Greens",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 85.29,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mint Leaves",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 58.24,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "G.nut oil Rice Bron 1 lt",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 139.11,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "G.nut oil Premium1 lt",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 163.80,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Ground nut oil 1 lt",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 158.49,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "G.oil Net rich 500 ml",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 78.14,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Fruit Juice Tailand",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 21.42,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Tender Coconut(S)",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 25.85,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Pista",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 178.48,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Thinda",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 74.23,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Tamarind seedless",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 195.71,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Straw Berry",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 144.56,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Litchi Local",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 331.86,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Kiwi fruit",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 521.36,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Grapes Krishna sharad",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 148.26,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{ 
   name: "Grapes Flame",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 105.46,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Grapes Sonika",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 137.48,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Grapes Sharad",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 139.23,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Grapes Dilkush",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 85.26,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "GrapesAnabi shahi",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 28.36,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Hesaru kalu",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 141.41,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Molake kalu",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 114.82,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Greens Sabbakki",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 77.08,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Parvala",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 100.79,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Spring Onion(Cleaned)",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 86.91,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Spring Onion",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 83.97,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Chocolates Drink box",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 53.53,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Fanda",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 44.64,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Jam 100 gm",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 26.75,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Jam 200 gm",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 44.60,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Jam 1/2 kg",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 98.17,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Jam 1 kg",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 133.84,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Coconut oil 500 ml",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 126.52,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Stevia powder",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 107.08,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Pepper",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 124.91,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Sungold oil 5 lt packet",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 713.87,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Sun safal Tin 15 lt",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 845.91,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Safal deep 500 ml",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 66.70,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Ground nut oil 5 lt",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 1007.24,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Sungold oil 5 lt",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 765.01,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Rice Bran 5 lt",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 716.54,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Tamarind Paste 150 gm",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 61.91,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Indian red globe",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 214.06,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Peas seeds",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 305.86,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Anjura/Fig",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 115.76,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Butter fruit",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 138.76,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Bore fruit",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 36.44,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "S.mellon Local (Luck)",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 59.48,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Chilles small cleaned (C.B.P)",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 99.74,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Times Rose berry",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 218.49,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Chikkadikai cleaned",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 75.89,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Orange juice",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 24.98,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Thiland Jelly",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 35.69,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Thiland Juice",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 21.41,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Pineapple juice",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 117.80,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mosambi",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 91.72,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "S.mellon namdhari",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 34.62,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Watermellon kiran",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 29.97,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Watermellon",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 25.09,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Tamarind sweet 500gm",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 184.04,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Rose apple",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 243.24,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Plum Australia",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 533.22,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Pineapple",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 64.88,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Papaya sola",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 59.72,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Papaya Red lady",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 36.20,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Papaya Taiwan",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 34.65,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Papaya nati",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 22.90,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Pomegranate A.raktha",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 153.07,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Pomegranate Bhagav",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 225.26,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Dhantu greens",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 55.07,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Curry leave",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 85.26,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Corriander Leave",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 63.20,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Kakadi",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 78.57,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Pickles mixed veg",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 89.24,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "mango Pickles",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 107.08,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Lime Pickles",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 116.03,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Pickles",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 98.14,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Rice Bran 15 lt Tin",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 1424.26,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "G. nut sungold 1 lt",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 150.04,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "G. nut Golden oil 1 lt",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 197.79,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "G. nut oil safal deep1 lt",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 130.89,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Apple juice",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 117.81,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Litchi Juice",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 117.80,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Parsley",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 278.62,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Leeks",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 224.12,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Selari",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 185.66,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Chikkadikai Round",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 55.64,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mineral water 1 lt",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 26.75,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Net rich 5 lt oil",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 526.65,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Byladha Hannu",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 48.66,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Maize",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 27.21,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Y.Bananan T.N.",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 256.29,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Chain Berry",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 187.93,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Letteus Greens",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 193.17,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Basale Greens",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 56.09,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "BaleDindu (Banana stem)",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 35.62,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Batani kalu",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 352.42,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Sweet corn",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 55.80,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Orange Australia",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 200.13,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Orange Nagpura",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 99.14,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Cluster Bean Local",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 49.17,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mangalore cucumber",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 30.35,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Cucumber Israle",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 55.69,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Cucumber Nati",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 54.49,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Cucumber",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 31.18,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Chow-Chow",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 41.11,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Bottle Gourd",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 36.00,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Dry fruit mixed",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 151.62,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Dry dates",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 185.92,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Peas Delhi",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 90.67,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Peas local",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 223.98,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Onion samber",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 86.25,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Onion small(Economy)",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 17.45,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Jack fruit",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 26.63,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Onion Big",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 44.33,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Onion medium",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 40.93,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mushroom Oyster",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 179.17,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Brucoli",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 294.39,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Avare seed (FB seeds)",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 156.40,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Avarebele (F. Beans spok)",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 281.52,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Bale hoovu(B.flower)",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 33.42,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Sweet corn seeds",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 84.10,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Kashini (Ganike) Greens",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 13.67,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Gulkan 1/4 kg",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 53.59,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Gulkan 1/2 kg",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 71.39,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Gulkan 1 kg",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 142.72,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Honney 100 gm",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 51.74,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Honney 200 gm",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 96.35,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Honney 1 Kg",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 342.67,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Honney 1/2",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 187.46,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Copra",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 188.57,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Cauliflower(B)",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 47.74,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Cabbage chaina",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 82.72,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Cabbage Red",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 92.99,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Cabbage",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 28.39,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Coconut (OS)",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 18.27,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Coconut (S)",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 23.69,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Coconut (M)",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 30.01,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Coconut (B)",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 34.59,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Cowpea Long",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 71.59,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Carrot Nati",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 61.12,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Carrot Delhi",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 46.87,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Chillies small (C.B.P)",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 96.63,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Chillies Cleaned",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 55.80,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Chillies Bajji",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 53.80,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Chillies Green",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 56.93,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Capsicum Red/Yellow",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 160.66,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Capsicum",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 60.62,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mango Raw",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 68.15,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Thogari kai",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 52.89,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Tomoto",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 30.27,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Bitter Gourd",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 48.74,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Yam/S.Root",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 59.70,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Beet Root",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 41.76,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Brinjal Bottle",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 54.55,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Brinjal (R)",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 37.06,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Brinjal (W)",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 48.96,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Beans cleaned",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 68.52,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Beans",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 66.71,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Amla",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 89.07,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "N.Juice 200 ml",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 26.75,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Pomegranate Juice",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 117.77,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Brahmi amla juice",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 124.97,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Jumbu juice",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 223.13,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "G. nut oil Rice 1 lt",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 107.52,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Onion flowers",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 34.78,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Pomegranate Ganesh",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 119.09,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Grapesh Tash ganesh",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 107.37,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Peas Dharwad",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 14.16,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Papaya red indian",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 37.17,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Peas Ooty",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 124.08,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Grapes Crimson",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 48.99,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Indian Black globe Grapes",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 145.78,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Nagapur Orange Economy",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 9.76,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mango thotapuri",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 53.55,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mango Sendura",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 47.21,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "S.mellon namdhari (Red)",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 35.43,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Cucumber white",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 34.92,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mango Alphans",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 72.85,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mango Raw Amblet",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 54.77,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mango Badami",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 68.12,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mango Raspuri",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 52.83,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "South Af.red berry",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 368.52,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Apple Chilli",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 149.32,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Carrot ooty",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 71.97,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mango Bygan palli",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 50.12,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mango malagova",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 80.01,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Cluster Beans Bunches",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 25.77,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mango mallika",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 73.73,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mango Dasheri",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 64.26,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mango kalapadu",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 46.50,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Litchi Taiwan/chaina",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 369.55,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mango sakkaregutti",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 40.75,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Rumenia Mango",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 74.14,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Apple Chaina Delicious",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 264.54,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mango Amarpalli",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 40.72,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mango Kesar",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 40.83,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mango",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 23.46,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Jambo fruit(Nerale)",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 282.98,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mango Neelam",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 47.16,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Grapes Rose",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 71.34,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Berry fruit Ooty",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 26.64,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Plum Ooty",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 180.18,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Orange",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 60.97,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Beans Fruit",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 69.99,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Apple hazarath palli",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 154.60,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Peaches",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 258.89,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Komark fruit",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 38.58,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Sweet corn seeds spok",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 49.95,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Berry Golden",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 287.02,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Apple Simla",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 122.57,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Ginger New",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 83.62,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Cherry Tomoto",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 121.79,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Tamrind Chatisghar",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 103.91,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Tender Coconut",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 33.45,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mango rathnagiri(red)",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 32.57,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Berry Southafrica",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 211.33,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mango Alphans box",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 116.42,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Bread fruit",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 73.35,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Apple Australia",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 188.52,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Potato Baby",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 52.38,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Orange South Africa",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 148.57,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Apple Golden delicious",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 95.45,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Washington gala apple",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 160.07,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Pomello/Chakotha",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 40.30,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "South Africa Gala apple",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 47.46,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Berry Soft",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 209.21,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Berry Green",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 224.57,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Washington red apple",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 126.41,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Dry apricot",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 20.02,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Berry ball",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 92.22,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Cherry kashmir",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 497.87,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Sweet corn cleaned",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 125.14,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Tamarind Paste 450 gm",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 164.01,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Cucumber Ooty",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 212.01,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mosambi polo",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 31.04,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Beans Nati",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 28.14,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Orange Ooty",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 76.75,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Mango Langada",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 57.70,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Beans Ring",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 23.58,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Cherry fruit",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 110.77,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Chillies Bajji yagani",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 51.25,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
},
{
   name: "Tender Coconut(M)",
   category: 'Shirts',
   image:'/images/Sponge Gourd.jpeg',
   price: 27.16,
   countInStock: 10,
   brand: 'Nike',
   rating: 4.5,
   numReviews: 10,
   description: 'high quality product',
}

  ],
};
export default data;